In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font size="5" color="red">연관분석</font>
# 1. 연관분석 개요
- 데이터들 사이에 자주 발생하는 속성을 찾고, 그 속성들 사이에 연관성이 어느정도 있는지 분석
- 활동분야 : 이벤트 미리 감지, 신상품 카테고리 분석

# 2. 연관분석 구현

In [4]:
import csv
transaction = []
with open('data/cf_basket.csv', 'r', encoding='utf-8') as f :
    csvdata = csv.reader(f)
    transaction = list(csvdata)
transaction

[['소주', '콜라', '와인'],
 ['소주', '오렌지주스', '콜라'],
 ['맥주', '콜라', '와인'],
 ['소주', '콜라', '맥주'],
 ['오렌지주스', '와인']]

In [5]:
from apyori  import apriori
rules = apriori(transaction,
               min_support=0.15,
               min_confidence=0.1)
rules = list(rules)
len(rules)

18

In [6]:
rules[10]

RelationRecord(items=frozenset({'콜라', '소주'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'콜라', '소주'}), confidence=0.6, lift=1.0), OrderedStatistic(items_base=frozenset({'소주'}), items_add=frozenset({'콜라'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'콜라'}), items_add=frozenset({'소주'}), confidence=0.7499999999999999, lift=1.2499999999999998)])

In [16]:
rule = rules[10]
support = rule[1]
order_st = rule[2]
for item in order_st:
    lhs = item[0]
    rhs = item[1]
    confidence = item[2]
    lift = item[3]
    if lift > 1:
        print("{}=>{}\t {}\t {}\t {}".format(lhs, rhs, support, 
                                             round(confidence,2), 
                                             round(lift,2)))

frozenset({'소주'})=>frozenset({'콜라'})	 0.6	 1.0	 1.25
frozenset({'콜라'})=>frozenset({'소주'})	 0.6	 0.75	 1.25

In [17]:
for rule in rules:
    support = rule[1]
    order_st = rule[2]
    for item in order_st:
        lhs = item[0]
        rhs = item[1]
        confidence = item[2]
        lift = item[3]
        if lift > 1:
            print("{}=>{}\t {}\t {}\t {}".format(lhs, rhs, support, 
                                                 round(confidence,2), 
                                                 round(lift,2)))

frozenset({'맥주'})=>frozenset({'콜라'})	 0.4	 1.0	 1.25
frozenset({'콜라'})=>frozenset({'맥주'})	 0.4	 0.5	 1.25
frozenset({'소주'})=>frozenset({'콜라'})	 0.6	 1.0	 1.25
frozenset({'콜라'})=>frozenset({'소주'})	 0.6	 0.75	 1.25
frozenset({'콜라'})=>frozenset({'맥주', '소주'})	 0.2	 0.25	 1.25
frozenset({'맥주', '소주'})=>frozenset({'콜라'})	 0.2	 1.0	 1.25
frozenset({'맥주'})=>frozenset({'콜라', '와인'})	 0.2	 0.5	 1.25
frozenset({'콜라'})=>frozenset({'맥주', '와인'})	 0.2	 0.25	 1.25
frozenset({'맥주', '와인'})=>frozenset({'콜라'})	 0.2	 1.0	 1.25
frozenset({'콜라', '와인'})=>frozenset({'맥주'})	 0.2	 0.5	 1.25
frozenset({'소주'})=>frozenset({'콜라', '오렌지주스'})	 0.2	 0.33	 1.67
frozenset({'콜라'})=>frozenset({'오렌지주스', '소주'})	 0.2	 0.25	 1.25
frozenset({'오렌지주스', '소주'})=>frozenset({'콜라'})	 0.2	 1.0	 1.25
frozenset({'콜라', '오렌지주스'})=>frozenset({'소주'})	 0.2	 1.0	 1.67
frozenset({'콜라'})=>frozenset({'와인', '소주'})	 0.2	 0.25	 1.25
frozenset({'와인', '소주'})=>frozenset({'콜라'})	 0.2	 1.0	 1.25

In [27]:
import pandas as pd

# 빈 데이터프레임 만들기
rules_df = pd.DataFrame(columns=['lhs', 'rhs', '지지도', '신뢰도', '향상도'])

idx = 0
for rule in rules:
    support = rule.support
    order_st = rule.ordered_statistics
    for item in order_st:
        lhs = ', '.join([data for data in item.items_base])   # 왼쪽 항목들
        rhs = ', '.join([data for data in item.items_add])    # 오른쪽 항목들
        confidence = item.confidence
        lift = item.lift
        if lift > 1:
            rules_df.loc[idx] = [lhs, rhs, support, round(confidence, 2), round(lift, 2)]
            idx += 1

rules_df.sort_values(by=['향상도','신뢰도'], ascending=False)

          lhs        rhs  지지도   신뢰도   향상도
13  콜라, 오렌지주스         소주  0.2  1.00  1.67
10         소주  콜라, 오렌지주스  0.2  0.33  1.67
0          맥주         콜라  0.4  1.00  1.25
2          소주         콜라  0.6  1.00  1.25
5      맥주, 소주         콜라  0.2  1.00  1.25
8      맥주, 와인         콜라  0.2  1.00  1.25
12  오렌지주스, 소주         콜라  0.2  1.00  1.25
15     와인, 소주         콜라  0.2  1.00  1.25
3          콜라         소주  0.6  0.75  1.25
1          콜라         맥주  0.4  0.50  1.25
6          맥주     콜라, 와인  0.2  0.50  1.25
9      콜라, 와인         맥주  0.2  0.50  1.25
4          콜라     맥주, 소주  0.2  0.25  1.25
7          콜라     맥주, 와인  0.2  0.25  1.25
11         콜라  오렌지주스, 소주  0.2  0.25  1.25
14         콜라     와인, 소주  0.2  0.25  1.25

# 3. 경주/전주 여행 자료 연관분석

In [42]:
import pandas as pd
from konlpy.tag import Hannanum
df = pd.read_csv('data/naver_kin.csv', sep='\t')
total_text_list = df['total_text'].to_list()
#total_text_list[:2]
analyzer = Hannanum()
total_noun_list = []
select_pos=['NC',"NQ"]  # 보통명사, 고유명사
불용어 = {'여행'}
for total_text in total_text_list:
   # total_noun = analyzer.nouns(total_text)
    total_noun = [token for token, tag in analyzer.pos(total_text, ntags=22)
                  if tag in select_pos and
                 token not in 불용어 and
                 len(token)>1]
    total_noun_list.append(total_noun)
print(total_noun_list)

[['전주', '가볼만한곳', '추천', '추억', '다양한체험', '7080감성', '추억여행', '테마박물관', '유익한시간', '전북투어패스', '통합이용권', '전북핫플', '여러여행지', '다양한체험', '카페이용추', '전주여행', '편안', '되시길', '감사'], ['전주여행', '전주여행', '아는사람', '호텔', '좋은가격', '2박3일여행인데', '얼마정도갖고가면좋을까요', '맛집같은거', '카페같은거', '추천', '안녕', '전주', '계획', '한옥마을', '근처'], ['전주', '관련', '질문', '전주', '계획하', '선택', '전주', '한옥마을', '자연경관', '음식', '가득', '동네', '시간', '거예요', '한옥마을', '근처', '장소'], ['중2', '여학생', '친구', '전주여행', '안녕', '여학생', '친한친구', '전주', '막막', '둘다', '애니', '좋아하는데전주', '오타쿠들'], ['부모닝', '전주여행', '부모님', '전주여행', '명소', '식당', '추천부탁드', '전주', '한옥마을', '유명', '완산구', '덕진구', '추억', '장소'], ['2박3', '전주여행', '이번주', '2박3', '여자친구', '전주여행', '여행경', '토요일', '실내데이트', '가능한곳', '감사', '숙소', '전주한옥마을', '근처', '한옥마을', '구경'], ['전주', '1박2', '저녁', '전주천', '산책길', '한옥마을', '근처', '야경', '일정', '관심', '테마', '카페', '체험', '추천', '전주', '되시길', '바랄게요'], ['전주', '코스', '추천이요~', '영화제', '기간', '일정', '2박3', '전주여행', '여행코스', '추천', '주목적', '전주국제영화제', '못할거에요', '전주하', '알짜배', '추천해주세욜', '전주'], ['전주', '전주', '커플여행', '추천', '숙소', '맛집', '추천', '감사', '한옥마을', '답변', '도움', '한옥마을', '전주한옥마을', '전주', '맛집', '전주', '전주', '추천'], ['추석', '전주여행', '전주', '한옥마을', '관광지들', '추석당일', '전주', '이벤트', '진행', '한국관광공사', '숙박세일', '페스타', '이벤트', '진행'], ['전주', '연령', '렌트카', '추천', '전주', '2박3일', '전주', '연령', '자동차', '추천좀', '가격', '렌트하', '어느정도', '전주', '이상', '렌트', '가능', '자동차', '가격'], ['전주', '-포항', '전주', '포항까지', '기차', '버스', '안녕', '전주', '포항까지', '기차', '버스', '장단점', '방법', '결정', '요소', '필요'], ['전주', '펜션', '한옥', '된곳이요', '남자친구', '2박3', '전주여행', '가기로해', '전주펜션', '한옥마을', '근처', '한옥느낌', '전주펜션', '내부', '정감', '분위기', '빠른답변', '부탁드랴용'], ['전주', '전주', '한옥마을', '유명', '완산구', '덕진구', '추억', '장소', '완산구', '덕진구'], ['전주', '뚜벅', '엄마', '전주', '뚜벅', '계획', '답변', '부탁', '기차', '고속버스', '어떤걸', '전주', '도착', '관광', '이용', '교통수단', '어떤', '숙소', '추천', '서울'], ['전주', '당일치기', '전주', '당일치기', '계획', '전주', '한옥마을', '방법', '당일치기', '코스', '알려드릴게요', '전주', '한옥마을', '방법', '택시', '버스', '전주', '한옥마을', '택시'], ['전주여행', '2박3', '경비', '전주여행', '2박3', '경비', '얼마정도', '숙소', '질문', '도움', '답변', '되셨길', '2박3', '전주여행', '예산', '내외', '숙소', '적당'], ['1박2', '전주', '커플', '전주', '도움', '드릴게요', '남자친구', '이용', '이용', '요소', '교통체증', '예상', '날짜', '이용', '남자친구'], ['남해', '전주', '남해', '전주', '여행지', '맛집', '추천좀', '보리암', '다랭이굴', '독일마', '전주', '한옥마을빼', '두세개씩5명이서', '갈곳', '맛집', '빨리추천해주세요', '말했던곳', '갈꺼라서', '추천안해주', '전주여행', '전주맛집'], ['전주여행', '갈곳', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을'], ['전주여행', '1박2', '코스질문요', '코스한번짜주실분', '전라도', '저도여행을간적이없어서', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언'], ['전주여행', '전주여행', '비용', '얼마', '전주', '비용', '요소', '일반적', '다음', '항목들', '포함', '교통비', '전주', '이동하기', '교통비용'], ['전주여행', '코스', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을', '시작'], ['전주', '당일치기', '코스', '추천', '박물관', '미술관', '지역', '공간', '스토리', '안내', '해설형', '문화', '코스', '노쇼', '방지', '예약금', '결제', '현장', '상당', '음료', '기프티콘', '환급', '선착순', '마감', '전주', '계획'], ['전주여행', '필요', '안녕', '1박2', '전주여행', '계획', '서울', '전주', '기차를타고갈건데', '전주내', '렌트', '궁금', '참고', '전주한옥마을', '포함해서', '유명', '관광지', '돌아볼계획입니다', '전주여행', '전주맛집', '국내여행'], ['전주여행', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주', '대중교통', '택시', '이용하시는걸'], ['전주', '완주', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '완주', '어느쪽', '여행하느냐'], ['전주', '3박4', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스'], ['전주여행', '코스좀짜주세요ㅜㅜ', '전주여행', '코스', '전주', '역사적', '유적지', '전통문화', '유명한데요', '전주한옥마을', '방문하시', '한옥', '아름다움', '시작지', '전주한옥마을'], ['전주여행', '대중교통', '렌트카중', '어떤', '전주여행', '대중교통', '교통', '상황', '어떤지', '궁금', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['전주', '전주', '전주', '연인들', '추천', '전주한옥마을', '전주동물원', '한국도로공사수목원', '전주향교', '덕진공원'], ['전주여행', '관련', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '주말', '평일', '따라다릅니'], ['전주', '1박2일vs2박3', '어떤', '적당', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이'], ['전주', '이번주', '전주', '추천', '위주', '트레킹', '전주여행', '계획', '전주', '다양한', '볼거리들'], ['전주', '2박3', '경비', '식비', '교통비', '안잡혀서요', '안마', '술값', '한번마', '쓸거같아요', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳'], ['전주', '2박3', '비용', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '한옥마을', '입장료', '따로없습니다', '기본'], ['친구', '전주여행', '친구', '전주여행', '가볼만한곳', '호텔', '맛집', '추천', '호텔', '시설', '깨끗', '한옥', '침대', '있는곳', '맛집', '양식', '상관', '비용', '1인당'], ['2박3', '전주', '크리스마스', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을', '시작'], ['1박2', '전주여행', '질문', '전주', '일정', '관련', '답변', '여행가', '계획짜', '전주', '준비해', '아래', '일정', '여행되시길'], ['초등', '전주', '1박2', '수학', '코스', '전주', '관광', '달인', '전주달봉이님께서', '코스', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['1박2', '전주', '코스', '질문', '전주', '정보', '정리', '전주', '덕진공원', '추천', '덕진공원', '전주터미널', '산책', '호수공원', '덕진공원', '생략', '남부시장'], ['전주여행', '갈곳,', '전시회', '추천', '이번달', '남자친구', '전주여행', '전주한옥마을', '공방', '전시회같은거', '추천부탁드', '안녕', '질문', '전주여행', '관련', '답변', '전주', '놀러가시'], ['전주여행', '코스', '추천', '안녕', '여자친구', '전주여행', '갈예정', '숙소', '전주', '더클래식호텔', '1박2', '일정', '근데', '금요일', '오후', '전주', '도착예정', '자가차', '이동수단', '대중교통', '택시', '할예정'], ['전주', '거리', '추석', '여행예정', '갈만한곳', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['전주여행', '갈만한곳있을까요', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을'], ['전주', '코스', '전주여행', '일정', '질문자', '반양하', '시간상', '무리', '일정', '가운데집', '점심', '전주한지박물관', '관광', '전주수목원', '관광', '오목대', '관광', '교동다윈'], ['전주여행', '추천', '부탁', '전주', '할려구', '1박2', '가볼만한곳이랑', '맛집', '추천', '감사', '전주맛집', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '인플루언서', '전주달봉이입니다', '전주여행'], ['강아지와함께', '전주여행', '가능한곳ㅜ', '전주여행', '갈껀데요', '강아지', '동반할꺼라서요', '강아지', '갈수있는곳좀', '맛집이랑', '관광징', '반려동물', '여행앱', '반려생활', '하늘', '가을', '전주', '강아지', '추억'], ['광주', '전주', '2박3', '감사', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '버스터미널'], ['전주여행', '코스', '질문', '전주', '일정', '관련', '답변', '친정', '어머니', '아래', '일정', '준비해', '도움'], ['추천', '전주', '당일치기', '추천', '전주', '당일치기', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이'], ['전주여행', '팀조뮤ㅠ', '전주여행', '1박2일가는데가기좋은곳이랑맛집좀알려주세요', '안녕', '서울지방변호사회', '소속', '지식iN', '법률상담', '진행', '김선용', '변호사', '인스타그램', '전주', '검색'], ['전주', '한옥마을', '준비중', '천차만별', '기본', '금액', '부터시작합니다', '한복에따라서', '가격이다릅니다', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['고등학교친구들', '전주여행', '당일치기', '고등학교3학년', '친구들', '전주여행', '당일치기', '예정', '부모님', '허락', '고등학교', '시절', '친구들', '소중', '추억', '전주', '전주'], ['전주', '휴가갈건데', '코스', '추천', '일정', '참고용', '제시', '일정', '조정', '음식점', '웨이팅', '방문', '요일', '전주', '되시길'], ['여자2명이서2박3일', '전주여행', '질문', '전주', '다음', '일정', '추천', '전주', '한옥마을', '전통', '한옥', '건물', '전통', '문화', '경험', '전주', '향교', '조선시대', '교육기관', '향교', '전주', '남부시장', '전주'], ['전주', '코스', '안녕', '가족', '전주', '놀러가려는데요', '이번주', '금요일', '어딜갈지', '숙소', '라한호텔', '한옥마을', '카페투어', '코스', '호캉스'], ['전주', '1박2', '대둔산', '케이블카', '주말', '사람많겠죠', '코스', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문'], ['전주', '코스', '전주여행', '복귀', '지난주', '당일코스', '전주', '주말', '관광지', '사람들', '생각', '최소한', '1박2'], ['전주', '한옥마을', '당일치기', '질문', '전주여수제주도맛집', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '흐노니', '마시랑게', '전망', '달곰'], ['전주', '혼자2박3', '사람', '맛집같은곳', '혼자못먹을것같아서', '중순', '전주', '계절', '현재', '코로나19', '여행객', '사람', '예상', '전주', '맛집'], ['전주', '이번달', '친구', '전주', '궁금', '답장', '감사하겟습니다', '여수', '전주', '왕복', '기차표값', '얼마', '중2들', '전주'], ['전주여행', '갈껀데', '월요일', '휴무', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '걱정안하셔도되', '대부분', '오픈'], ['전주', '당일치기', '부모님', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '바다', '군산', '새만금'], ['전주여행', '안녕', '가족들', '전주여행', '한옥마을', '유명', '전주여행', '기회', '다녀와보려구요', '음식', '전주', '전라도', '대표음식', '맛집'], ['전주', '코스', '추천', '전주', '코스', '추천', '전주여수맛집', '전주여행', '여수여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '대부분', '한옥마을', '시작'], ['전주여행', '이번주', '전주여행', '맛집', '전주', '추천', '전주한옥마을', '전주동물원', '한국도로공사수목원', '덕진공원', '전주난장'], ['전주', '오션뷰', '카페', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주', '바다가없어'], ['전주', '가족', '코스', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을'], ['전주', '코스', '일정', '추천', '부탁드려요(토요', '하루', '일정', '수정', '필요', '부분', '인근', '맛집', '의견', '부탁', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['전주', '전주', '한옥마을', '근처', '숙박', '어디어디', '맛집', '버스', '택시타', '어딘지', '추천', '다른곳'], ['전주', '코스', '아침', '전주', '현대옥', '본점', '점심', '전주', '비빔소리', '현대옥', '비빔소리', '중간', '구경', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스'], ['전주여행', '전주', '한번도안가봐서요', '1박2일', '2박3', '있을예정', '가볼만한곳', '추천받아용', '체험도좋구용', '전주', '추천', '전주', '한옥마을'], ['전주', '참고', '뚜벅', '입니댜', '전주', '계획', '전주', '가볼만한곳들', '추천', '한국도로공사수목원', '전주동물원', '자만마을', '벽화갤러리', '국립전주박물관'], ['전주', '코스', '추천', '전주', '코스', '추천', '안녕', '전주맛집', '전주블로그', '전주달봉이입니다', '대부분', '1박2', '코스로들', '전주', '한옥마을', '경기전', '남부시장야시장', '벽화', '전동성당', '향교', '오목대', '이렇게들', '많이들', '추가'], ['전주', '코스', '숙소', '완산구', '서신동', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '한옥마을'], ['전주여행', '크리스마스', '단둘이', '당일치기', '전주여행', '하기로했습니다', '고등학생인데요', '어느정도', '들고가는게맞고', '전주', '뭐뭐', '답변', '대학', '투어공연', '연극', '추천해'], ['전주여행', '왜그런진', '사투리', '억양', '쎄서그런감', '거북', '전주여행', '무슨일인진모르겠지만', '사람들', '사투리', '안쓰던데요', '의외', '전라북', '전주시'], ['전주', '1박2', '코스', '추천', '조언', '가고싶은곳', '전주한옥마을', '경기전', '전주난장', '전주국립박물관', '전주동물원', '이동수단', '자동차', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['뚜벅', '전주', '한옥마을', '근처', '이용하시', '장소', '장소', '운송', '가능', '가격', '실시간', '주문', '현황', '확인', '가능', '편리', '이용', '가능', '전주', '뚜벅이여행', '전주여행', '되시길', '바랄게요'], ['전주', '일정', '전주', '소요시간', '한옥마을', '초코파', '체험장', '수목원', '드림랜드', '이동시간', '자세', '부탁드릴게요', '전주', '한옥마을내', '초코파이체험장', '이걸'], ['태교', '2박3', '놀러가려', '강아지', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '숙소잡기', '바닷가'], ['전주여행', '추천', '전주여행', '추천', '전주식', '가맥문화', '전일슈퍼', '전주만', '문화', '에피큐', '평점', '전주식', '한정식', '최고봉', '수구정', '전라회관', '전주비빔밥', '최고봉', '고궁', '성미당', '토종', '명품닭', '사용', '닭요리'], ['1박2', '전주', '코스', '질문', '전주', '정보', '정리', '전주', '덕진공원', '추천', '덕진공원', '전주터미널', '산책', '호수공원', '덕진공원', '생략', '남부시장'], ['전주', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을', '시작'], ['2박3', '전주여행', '부모님', '전주여행', '정보', '숙소', '어디가좋은지', '관광지', '어디가있는지', '추천부탁드', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행'], ['전주', '코스', '전주여행', '복귀', '지난주', '당일코스', '전주', '주말', '관광지', '사람들', '생각', '최소한', '1박2'], ['전주', '당일치기', '질문', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '기지제', '산책', '저녁', '많이들'], ['전주', '1박2', '코스추천부탁드', '남자친구', '생일여행', '전주여행', '을가는데', '전주', '처음', '코스', '추천좀', '숙소', '전주', '한옥마을', '도보', '자차', '문제', '맛집', '추천', '안녕'], ['전주', '한옥마을', '예정', '욕조', '무리한', '질문', '혹시나해서', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언'], ['전주', '렌트', '전주', '렌트', '안녕', '반려인', '애견', '동반', '플랫폼', '하트독', '전주', '도시', '택시', '이동을해', '불편함', '답변', '도움', '채택', '부탁드'], ['전주', '코스', '질문드', '이상', '전주여행', '문의', '안내', '정보', '질문', '요약', '사이트', '예약하시', '오전'], ['전주', '코스', '질문', '내공있어요~100', '부산', '전주여행', '자차', '버스위주', '전주', '가는것이아니라', '전주갔다', '전주', '버스', '정도', '지역', '다니시는분들'], ['전주', '코스', '추천좀요', '전주', '코스', '추천하세염', '전주동물원', '걍기전', '전주한옥마을', '덕진연못', '가보'], ['전주여행', '코스', '안녕', '전주', '당일치기', '할껀데', '코스', '전주', '동물원', '전주', '한옥마을', '전주', '수목원', '팔복예술공장', '전주', '드림랜드', '당일치기', '갈껀데', '코스좀알려주세요', '자가용', '이동', '아래', '코스', '시간'], ['1박2', '전주', '코스', '질문', '전주', '코스', '관련', '답변드', '가족', '전주', '계획', '전주', '추천', '명소', '맛집들', '포함', '여다', '맞춤형', '전주', '코스', '준비', '아래', '첨부', '일정'], ['당일치기', '전주여행', '코스', '처음', '전주여행', '전주', '한옥마을', '한복', '한옥마을', '전동성당', '경기전', '자만벽화', '놀러갈', '찾진', '전주', '한옥마을'], ['초등', '아이', '전주여행', '코스', '맛집', '추천', '부탁', '아이', '전주', '계획하', '전주', '아이', '몇군데', '추천드', '전주', '한옥마을', '계획', '장소', '전주', '한옥마을', '한복', '한옥마을', '사진'], ['(급합니다ㅠㅠ)', '전주', '코스', '전주여행', '코스', '추천드', '안녕', '여행전문블로거', '쭈니아빠입니다', '방학', '친구분', '전주여행', '준비', '전주', '한옥마을', '중심', '터미널', '버스', '한옥마을'], ['전주여행', '순서좀', '전주여행', '덕진공원', '전주동물원', '한옥마을', '남부시장', '전주시외버스공용터미널', '순서', '근처', '바닷가', '구경'], ['전주여행', '전주여행', '아는사람', '호텔', '좋은가격', '2박3일여행인데', '얼마정도갖고가면좋을까요', '맛집같은거', '카페같은거', '추천', '안녕', '전주', '계획', '한옥마을', '근처'], ['전주', '관련', '질문', '전주', '계획하', '선택', '전주', '한옥마을', '자연경관', '음식', '가득', '동네', '시간', '거예요', '한옥마을', '근처', '장소'], ['중2', '여학생', '친구', '전주여행', '안녕', '여학생', '친한친구', '전주', '막막', '둘다', '애니', '좋아하는데전주', '오타쿠들'], ['부모닝', '전주여행', '부모님', '전주여행', '명소', '식당', '추천부탁드', '전주', '한옥마을', '유명', '완산구', '덕진구', '추억', '장소'], ['2박3', '전주여행', '이번주', '2박3', '여자친구', '전주여행', '여행경', '토요일', '실내데이트', '가능한곳', '감사', '숙소', '전주한옥마을', '근처', '한옥마을', '구경'], ['전주', '1박2', '저녁', '전주천', '산책길', '한옥마을', '근처', '야경', '일정', '관심', '테마', '카페', '체험', '추천', '전주', '되시길', '바랄게요'], ['전주', '코스', '추천이요~', '영화제', '기간', '일정', '2박3', '전주여행', '여행코스', '추천', '주목적', '전주국제영화제', '못할거에요', '전주하', '알짜배', '추천해주세욜', '전주'], ['전주', '전주', '커플여행', '추천', '숙소', '맛집', '추천', '감사', '한옥마을', '답변', '도움', '한옥마을', '전주한옥마을', '전주', '맛집', '전주', '전주', '추천'], ['추석', '전주여행', '전주', '한옥마을', '관광지들', '추석당일', '전주', '이벤트', '진행', '한국관광공사', '숙박세일', '페스타', '이벤트', '진행'], ['전주', '연령', '렌트카', '추천', '전주', '2박3일', '전주', '연령', '자동차', '추천좀', '가격', '렌트하', '어느정도', '전주', '이상', '렌트', '가능', '자동차', '가격'], ['전주', '-포항', '전주', '포항까지', '기차', '버스', '안녕', '전주', '포항까지', '기차', '버스', '장단점', '방법', '결정', '요소', '필요'], ['전주', '펜션', '한옥', '된곳이요', '남자친구', '2박3', '전주여행', '가기로해', '전주펜션', '한옥마을', '근처', '한옥느낌', '전주펜션', '내부', '정감', '분위기', '빠른답변', '부탁드랴용'], ['전주', '전주', '한옥마을', '유명', '완산구', '덕진구', '추억', '장소', '완산구', '덕진구'], ['전주', '뚜벅', '엄마', '전주', '뚜벅', '계획', '답변', '부탁', '기차', '고속버스', '어떤걸', '전주', '도착', '관광', '이용', '교통수단', '어떤', '숙소', '추천', '서울'], ['전주', '당일치기', '전주', '당일치기', '계획', '전주', '한옥마을', '방법', '당일치기', '코스', '알려드릴게요', '전주', '한옥마을', '방법', '택시', '버스', '전주', '한옥마을', '택시'], ['전주여행', '2박3', '경비', '전주여행', '2박3', '경비', '얼마정도', '숙소', '질문', '도움', '답변', '되셨길', '2박3', '전주여행', '예산', '내외', '숙소', '적당'], ['1박2', '전주', '커플', '전주', '도움', '드릴게요', '남자친구', '이용', '이용', '요소', '교통체증', '예상', '날짜', '이용', '남자친구'], ['남해', '전주', '남해', '전주', '여행지', '맛집', '추천좀', '보리암', '다랭이굴', '독일마', '전주', '한옥마을빼', '두세개씩5명이서', '갈곳', '맛집', '빨리추천해주세요', '말했던곳', '갈꺼라서', '추천안해주', '전주여행', '전주맛집'], ['전주여행', '갈곳', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을'], ['전주여행', '1박2', '코스질문요', '코스한번짜주실분', '전라도', '저도여행을간적이없어서', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언'], ['전주여행', '전주여행', '비용', '얼마', '전주', '비용', '요소', '일반적', '다음', '항목들', '포함', '교통비', '전주', '이동하기', '교통비용'], ['전주여행', '코스', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을', '시작'], ['전주', '당일치기', '코스', '추천', '박물관', '미술관', '지역', '공간', '스토리', '안내', '해설형', '문화', '코스', '노쇼', '방지', '예약금', '결제', '현장', '상당', '음료', '기프티콘', '환급', '선착순', '마감', '전주', '계획'], ['전주여행', '필요', '안녕', '1박2', '전주여행', '계획', '서울', '전주', '기차를타고갈건데', '전주내', '렌트', '궁금', '참고', '전주한옥마을', '포함해서', '유명', '관광지', '돌아볼계획입니다', '전주여행', '전주맛집', '국내여행'], ['전주여행', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주', '대중교통', '택시', '이용하시는걸'], ['전주', '완주', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '완주', '어느쪽', '여행하느냐'], ['전주', '3박4', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스'], ['전주여행', '코스좀짜주세요ㅜㅜ', '전주여행', '코스', '전주', '역사적', '유적지', '전통문화', '유명한데요', '전주한옥마을', '방문하시', '한옥', '아름다움', '시작지', '전주한옥마을'], ['전주여행', '대중교통', '렌트카중', '어떤', '전주여행', '대중교통', '교통', '상황', '어떤지', '궁금', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['전주', '전주', '전주', '연인들', '추천', '전주한옥마을', '전주동물원', '한국도로공사수목원', '전주향교', '덕진공원'], ['전주여행', '관련', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '주말', '평일', '따라다릅니'], ['전주', '1박2일vs2박3', '어떤', '적당', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이'], ['전주', '이번주', '전주', '추천', '위주', '트레킹', '전주여행', '계획', '전주', '다양한', '볼거리들'], ['전주', '2박3', '경비', '식비', '교통비', '안잡혀서요', '안마', '술값', '한번마', '쓸거같아요', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳'], ['전주', '2박3', '비용', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '한옥마을', '입장료', '따로없습니다', '기본'], ['친구', '전주여행', '친구', '전주여행', '가볼만한곳', '호텔', '맛집', '추천', '호텔', '시설', '깨끗', '한옥', '침대', '있는곳', '맛집', '양식', '상관', '비용', '1인당'], ['2박3', '전주', '크리스마스', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을', '시작'], ['1박2', '전주여행', '질문', '전주', '일정', '관련', '답변', '여행가', '계획짜', '전주', '준비해', '아래', '일정', '여행되시길'], ['초등', '전주', '1박2', '수학', '코스', '전주', '관광', '달인', '전주달봉이님께서', '코스', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['1박2', '전주', '코스', '질문', '전주', '정보', '정리', '전주', '덕진공원', '추천', '덕진공원', '전주터미널', '산책', '호수공원', '덕진공원', '생략', '남부시장'], ['전주여행', '갈곳,', '전시회', '추천', '이번달', '남자친구', '전주여행', '전주한옥마을', '공방', '전시회같은거', '추천부탁드', '안녕', '질문', '전주여행', '관련', '답변', '전주', '놀러가시'], ['전주여행', '코스', '추천', '안녕', '여자친구', '전주여행', '갈예정', '숙소', '전주', '더클래식호텔', '1박2', '일정', '근데', '금요일', '오후', '전주', '도착예정', '자가차', '이동수단', '대중교통', '택시', '할예정'], ['전주', '거리', '추석', '여행예정', '갈만한곳', '추천', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행'], ['전주여행', '갈만한곳있을까요', '전주여행', '전주맛집', '국내여행', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '여수여행', '여수가볼만한곳', '주도여행', '제주도가볼만한곳', '전문', '인플루언서', '전주달봉이입니다', '전주여행', '코스', '한옥마을'], ['전주', '코스', '전주여행', '일정', '질문자', '반양하', '시간상', '무리', '일정', '가운데집', '점심', '전주한지박물관', '관광', '전주수목원', '관광', '오목대', '관광', '교동다윈'], ['전주여행', '추천', '부탁', '전주', '할려구', '1박2', '가볼만한곳이랑', '맛집', '추천', '감사', '전주맛집', '전주달봉', '달봉티비', '전주여행', '코스', '전주가볼만한곳', '인플루언서', '전주달봉이입니다', '전주여행'], ['강아지와함께', '전주여행', '가능한곳ㅜ', '전주여행', '갈껀데요', '

In [44]:
%%time
rules = apriori(total_noun_list, min_support=0.15, min_confidence=0.3)
rules = list(rules)
len(rules)

CPU times: total: 1.11 s
Wall time: 1.11 s

644

In [45]:
rules_df.head(60)

          lhs        rhs  지지도   신뢰도   향상도
0          맥주         콜라  0.4  1.00  1.25
1          콜라         맥주  0.4  0.50  1.25
2          소주         콜라  0.6  1.00  1.25
3          콜라         소주  0.6  0.75  1.25
4          콜라     맥주, 소주  0.2  0.25  1.25
5      맥주, 소주         콜라  0.2  1.00  1.25
6          맥주     콜라, 와인  0.2  0.50  1.25
7          콜라     맥주, 와인  0.2  0.25  1.25
8      맥주, 와인         콜라  0.2  1.00  1.25
9      콜라, 와인         맥주  0.2  0.50  1.25
10         소주  콜라, 오렌지주스  0.2  0.33  1.67
11         콜라  오렌지주스, 소주  0.2  0.25  1.25
12  오렌지주스, 소주         콜라  0.2  1.00  1.25
13  콜라, 오렌지주스         소주  0.2  1.00  1.67
14         콜라     와인, 소주  0.2  0.25  1.25
15     와인, 소주         콜라  0.2  1.00  1.25